modules_right = []

[general]
	disable_mod = false
	hide_bossbar = true
	shadow_text = true
	auto_start = false
	animationSpeed = 1.0
	hide_debug_crosshair = true
	background_color = 1867534416
	space_modules = false
	always_show_profiler = false
	animations = true
	fontScale = 1.0
	hide_sidebar = true
	always_show_tps = false

[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	enabled = true

	[modules_left.lines]
		chunk_coords = false
		player_coords = true
		block_coords = false
		chunk_relative_coords = false

[[modules_left]]
	name = "location"
	name_color = 16777215
	value_color = 15658496
	enabled = true

	[modules_left.lines]
		light = false
		biome = true
		rotation = false
		facing = true
		slime_chunk = false
		local_difficulty = false
		day_ticks = false
		days_played = false
		dimension = false
		highest_block = false
		highest_block_server = false
		light_server = false

