
[General]
	#The Y coordinate for the container bar to display
	#Default: 4
	"Container Hud Y" = 4
	#The X coordinate for the container to display
	#Default: -124
	"Container Hud X" = -124
	#Position to anchor the widgets in
	#Options: TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	#Default: TOP_RIGHT
	#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	"Anchor Point" = "TOP_RIGHT"
	#The Y coordinate for the overuse to display
	#Default: 16
	"Overuse Hud Y" = 16
	#The X coordinate for the overuse to display
	#Default: -64
	"Overuse Hud X" = -64
	#The X coordinate for the fill bar to display
	#Default: -121
	"Fill Hud X" = -121
	#The Y coordinate for the fill bar to display
	#Default: 7
	"Fill Hud Y" = 7

