
[General]
	#Visibility when on fire while using a fire resistant fruit 
	#Default: 20
	#Range: 0 ~ 100
	"Fire Visibility" = 25
	#Changes the outline of the player's Haoshoku Haki, uses the hexadecimal format which MUST start with a # (ex: "#FF0000")
	#Default: #FF0000
	"Haki Color" = "#ff0000"
	#Always hold the leg up for combat as a Black Leg user
	#Default: true
	"Black Leg Always Up" = true

	[General."Cooldown Visuals"]
		Color = true
		Text = true

[UI]
	#Displays the cooldown, charge up time and any other number displayed in the ability icon as seconds instead of ticks
	#Default: false
	"Display in Seconds" = false
	#Displays the cooldown, charge up time and any other number displayed in the ability icon as seconds instead of ticks
	#Default: false
	#Range: 1 ~ 3
	"Ability Bars on Screen" = 1
	#Displays the keybind associated with the slot as text in the bottom-left part of it
	#Default: true
	"Show Keybind" = true

[System]
	#Allows the game to show a text message when the installed mod is outdated
	#Default: true
	"Update Message" = true

